version: 2
jobs:
  build:
    working_directory: ~/react-stencil

    docker:
      - image: circleci/node:carbon

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build project
          command: yarn build

  test:
    working_directory: ~/react-stencil

    docker:
      - image: circleci/node:carbon

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
